import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFDC52',
    paddingHorizontal: 20,
    paddingTop: 40,
  },
  header: {
    fontSize: 24,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 10,
    color: '#1f1f1f',
  },
  subHeader: {
    fontSize: 22,
    fontWeight: 'bold',
    marginBottom: 15,
    color: '#1f1f1f',
  },
  vehicleTypeContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: 10,
    marginBottom: 20,
    backgroundColor: '#FFDC52',
    paddingVertical: 10,
    borderRadius: 20,
  },
  pickerContainer: {
    borderColor: '#103E60',
    borderWidth: 2,
    borderRadius: 5,
    marginVertical: 10,
    overflow: 'hidden',
    marginTop: 10,
    paddingVertical: 8,
    paddingHorizontal: 12,
    alignItems: 'center',
    color: 'black',
  },
  vehicleIconContainer: {
    alignItems: 'center',
    backgroundColor: '#FFF',
    padding: 10,
    borderRadius: 15,
    width: 100,
    height: 100,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  vehicleType: {
    fontSize: 18,
    color: '#000',
  },
  selectedVehicleType: {
    fontSize: 18,
    color: '#fff',
    fontWeight: 'bold',
  },
  curvedPickerContainer: {
    backgroundColor: '#FFDF63',
    borderRadius: 20,
    overflow: 'hidden',
    height: 50,
    borderColor: '#103E60',
    borderWidth: 2,
  },
  selectedButton: {
    backgroundColor: '#8F1413',
  },
  vehicleContainer: {
    flexDirection: 'row',
    backgroundColor: '#FFDF63',
    borderRadius: 10,
    padding: 10,
    marginVertical: 10,
    alignItems: 'center',
    borderColor: '#103E60',
    borderWidth: 2,
  },
  vehicleImage: {
    width: 70,
    height: 70,
    borderRadius: 10,
  },
  vehicleDetails: {
    marginLeft: 20,
    flex: 1,
  },
  vehicleName: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#1f1f1f',
  },
  vehicleRate: {
    fontSize: 16,
    color: '#FF4500',
  },
  availableText: {
    fontSize: 14,
    color: 'green',
    marginTop: 5,
  },
  notAvailableText: {
    fontSize: 14,
    color: 'red',
    marginTop: 5,
  },
  bookButton: {
    marginTop: 10,
    paddingVertical: 8,
    paddingHorizontal: 12,
    backgroundColor: '#8F1413',
    borderRadius: 5,
    alignItems: 'center',
  },
  disabledButton: {
    backgroundColor: '#ccc',
  },
  bookButtonText: {
    color: '#fff',
    fontSize: 16,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContainer: {
    width: '80%',
    backgroundColor: '#FFE474',
    padding: 20,
    borderRadius: 20,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#1f1f1f',
  },
  modalVehicleName: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#103E60',
    marginVertical: 10,
  },
  modalNote: {
    marginVertical: 10,
    color: '#8F1413',
    fontSize: 12,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  termsContainer: {
    marginTop: 10,
    backgroundColor: '#FFDC52',
    padding: 10,
    borderRadius: 10,
  },
  termsTitle: {
    fontWeight: 'bold',
    marginBottom: 5,
    color: '#8F1413',
  },
  termsText: {
    color: '#000',
  },
  modalFooter: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: 20,
  },
  cancelButton: {
    backgroundColor: '#8F1413',
    padding: 10,
    borderRadius: 10,
    borderColor: '#8F1413',
    borderWidth: 2,
  },
  cancelButtonText: {
    color: '#fff',
  },
  confirmButton: {
    backgroundColor: '#8F1413',
    padding: 10,
    borderRadius: 10,
  },
  confirmButtonText: {
    color: '#fff',
  },
  iconImage: {
    width: 40,
    height: 40,
    marginBottom: 5,
  },
});

export const pickerSelectStyles = StyleSheet.create({
  inputIOS: {
    fontSize: 16,
    color: 'black',
    paddingVertical: 12,
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: '#FFE474',
    borderRadius: 4,
    paddingRight: 30,
    backgroundColor: '#FFE474',
  },
  inputAndroid: {
    fontSize: 16,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: '#FFE474',
    borderRadius: 8,
    color: 'black',
    paddingRight: 30,
    backgroundColor: '#FFE474',
  },
});
